export const PEPTIDES = [
  { id: 'sema', name: 'Semaglutide', class: 'GLP-1' },
  { id: 'tirz', name: 'Tirzepatide', class: 'GLP-1/GIP' },
  { id: 'reta', name: 'Retatrutide', class: 'GLP-1/GIP/Glucagon' },
  { id: 'cagri', name: 'Cagrilintide', class: 'Amylin analog' },
  { id: 'aod', name: 'AOD-9604', class: 'Fragment / metabolic' },
  { id: 'bpc', name: 'BPC-157', class: 'Repair' },
  { id: 'tb500', name: 'TB-500', class: 'Repair' },
  { id: 'cjc', name: 'CJC-1295 (no DAC)', class: 'GHRH' },
  { id: 'ipa', name: 'Ipamorelin', class: 'GHRP' },
  { id: 'cjc-ipa', name: 'CJC-1295 / Ipamorelin', class: 'Blend' },
  { id: 'tesa', name: 'Tesamorelin', class: 'GHRH' },
  { id: 'serm', name: 'Sermorelin', class: 'GHRH' },
  { id: 'ghk', name: 'GHK-Cu', class: 'Repair' },
  { id: 'kpv', name: 'KPV', class: 'Anti-inflammatory fragment' },
  { id: 'klow', name: 'KLOW', class: 'Blend' },
  { id: 'ta1', name: 'Thymosin alpha-1', class: 'Immune' },
  { id: 'selank', name: 'Selank', class: 'Anxiolytic peptide' },
  { id: 'semax', name: 'Semax', class: 'Nootropic peptide' },
  { id: 'dsip', name: 'DSIP', class: 'Sleep peptide' },
  { id: 'pinealon', name: 'Pinealon', class: 'Bioregulator' },
  { id: 'epithalon', name: 'Epithalon', class: 'Bioregulator' },
  { id: 'niacin', name: 'Niacin', class: 'Oral NAD precursor' },
  { id: 'nmn', name: 'NMN', class: 'Oral NAD precursor' },
  { id: 'nr', name: 'NR', class: 'Oral NAD precursor' },
  { id: 'foxo4', name: 'FOXO4-DRI', class: 'Senolytic peptide' },
  { id: 'pt141', name: 'PT-141', class: 'Melanocortin' },
  { id: 'oxytocin', name: 'Oxytocin', class: 'Neuropeptide' },
  { id: 'mt2', name: 'Melanotan II', class: 'Melanocortin' },
  { id: 'kiss', name: 'Kisspeptin', class: 'HPG axis' },
  { id: 'hcg', name: 'hCG', class: 'Gonadotropin' },
  { id: 'ha', name: 'Hyaluronic acid', class: 'Oral matrix' },
  { id: 'mots', name: 'MOTS-c', class: 'Mitochondrial' },
  { id: 'ss31', name: 'SS-31 (elamipretide)', class: 'Mitochondrial' },
  { id: 'nad', name: 'NAD+', class: 'Cofactor' },
]

export const DIAGNOSES = [
  'Type 2 diabetes',
  'Obesity / weight management',
  'Insulin resistance',
  'MASLD / fatty liver',
  'Tendon injury',
  'Ligament injury',
  'Post-surgical recovery',
  'Inflammatory bowel symptoms',
  'Joint pain',
  'Age-related GH decline',
  'Sleep disruption',
  'Body composition',
  'Skin / wound healing',
  'Other (specify in notes)',
]

export const FREQUENCIES = [
  'Daily',
  '5 days on / 2 off',
  'Every other day',
  'Twice weekly',
  'Weekly',
  'As directed',
]

export const ROUTES = ['Subcutaneous', 'Intramuscular', 'Oral', 'Topical', 'Nasal']

export const ASSAYS = [
  'HPLC-UV',
  'HPLC-MS',
  'Content vs label',
  'Endotoxin (LAL)',
  'Sterility',
  'Other (see notes)',
]

export const DEMO_LOTS = [
  {
    id: 'demo-lot-1',
    peptide: 'BPC-157',
    vendor: 'Demo vendor A',
    lot: 'BPC-2408-A12',
    lab_name: 'Partner lab (demo)',
    submitted_by: 'LAB-DEMO1',
    source: 'lab',
    method: 'HPLC-MS',
    verdict: 'pass',
    percent: '98.4',
    notes: 'Demo partner-lab row. Sterility not reported.',
    status: 'lab_attested',
    demo: true,
  },
  {
    id: 'demo-lot-2',
    peptide: 'Tirzepatide',
    vendor: 'Demo vendor B',
    lot: 'TZP-2601-09',
    lab_name: 'Independent lab (demo)',
    submitted_by: 'LAB-DEMO2',
    source: 'lab',
    method: 'HPLC-UV + content vs label',
    verdict: 'fail',
    percent: '73',
    notes: 'Demo fail so the board is not only clean COAs.',
    status: 'lab_attested',
    demo: true,
  },
  {
    id: 'demo-lot-3',
    peptide: 'BPC-157 / TB-500 blend',
    vendor: 'Demo vendor C',
    lot: 'WLV-2603-04',
    lab_name: 'Third-party lab (user-paid, demo)',
    submitted_by: 'PE-DEMO3',
    source: 'user_paid',
    method: 'HPLC-UV',
    verdict: 'pass',
    percent: '97.1',
    notes: 'User uploaded a paid COA. One vial is not a guarantee for the next vial in the same lot.',
    status: 'docs_checked',
    demo: true,
  },
]

export const PROTOCOL_TEMPLATES = [
  {
    id: 'if-reta-titration',
    name: 'Iron Forge retatrutide titration',
    peptide: 'Retatrutide',
    source: 'Josh Holyfield / Iron Forge Peptide Mastery (Skool)',
    frequency: 'Once weekly (same day). Optional split: half the weekly total, twice weekly.',
    schedule: [
      { weeks: '1–4', dose: '2 mg once weekly' },
      { weeks: '5–8', dose: '4 mg once weekly' },
      { weeks: '9–12', dose: '8 mg once weekly' },
      { weeks: '13+', dose: '12 mg once weekly (listed maximum)' },
    ],
    flags: [
      'Hold 4 more weeks at current step if side effects are rough',
      'Many stay at 8 mg; 12 mg is not required',
      'Split weekly total (e.g. 1 mg twice vs 2 mg once) is not the same as true microdosing',
    ],
  },
  {
    id: 'if-reta-cagri',
    name: 'Iron Forge retatrutide + cagrilintide',
    peptide: 'Retatrutide + Cagrilintide',
    source: 'Josh Holyfield / Iron Forge Peptide Mastery (Skool)',
    frequency: 'Once weekly, same day. Separate injections. Do not mix in one syringe.',
    schedule: [
      { weeks: '1–4', dose: 'Cagrilintide 0.25 mg (250 mcg) once weekly' },
      { weeks: '5–8', dose: 'Cagrilintide 0.5 mg once weekly' },
      { weeks: '9–12', dose: 'Cagrilintide 1.0 mg once weekly' },
      { weeks: '13–16', dose: 'Cagrilintide 1.7 mg once weekly' },
      { weeks: '17+', dose: 'Cagrilintide 2.4 mg once weekly (maintenance)' },
    ],
    flags: [
      'This card is the cagrilintide add-on while already on retatrutide',
      'Use with the Iron Forge retatrutide titration card, not instead of it',
    ],
  },
  {
    id: 'if-aod-std',
    name: 'Iron Forge AOD-9604 standard',
    peptide: 'AOD-9604',
    source: 'Josh Holyfield / Iron Forge Peptide Mastery (Skool)',
    frequency: 'Once daily, subcutaneous, morning fasted, wait ≥30 min before eating',
    schedule: [{ weeks: '4–12', dose: '300 mcg once daily' }],
    flags: ['Empty stomach'],
  },
  {
    id: 'if-aod-high',
    name: 'Iron Forge AOD-9604 higher dose',
    peptide: 'AOD-9604',
    source: 'Josh Holyfield / Iron Forge Peptide Mastery (Skool)',
    frequency: 'Once daily morning fasted, or split 250 mcg morning + 250 mcg before bed',
    schedule: [{ weeks: '4–12', dose: '500 mcg daily total' }],
    flags: ['Optional split: 250 mcg AM + 250 mcg HS'],
  },
  {
    id: 'if-mots-std',
    name: 'Iron Forge MOTS-c standard',
    peptide: 'MOTS-c',
    source: 'Josh Holyfield / Iron Forge Peptide Mastery (Skool)',
    frequency: '3 injections per week (Mon/Wed/Fri). Morning fasted or 30 min before training. SubQ.',
    schedule: [{ weeks: '4–8 on, then equal time off', dose: '5–10 mg per week total' }],
    flags: [
      'Community/practice pattern, not a published dose-finding study',
      'At least 3x/week',
    ],
  },
  {
    id: 'if-mots-training',
    name: 'Iron Forge MOTS-c training',
    peptide: 'MOTS-c',
    source: 'Josh Holyfield / Iron Forge Peptide Mastery (Skool)',
    frequency: '3 injections per week',
    schedule: [{ weeks: 'as standard cycle', dose: '5–10 mg per week total' }],
    flags: ['Goal: training enhancement'],
  },
  {
    id: 'if-mots-metabolic',
    name: 'Iron Forge MOTS-c metabolic',
    peptide: 'MOTS-c',
    source: 'Josh Holyfield / Iron Forge Peptide Mastery (Skool)',
    frequency: '3 injections per week',
    schedule: [{ weeks: 'as standard cycle', dose: '10–15 mg per week total' }],
    flags: ['Goal: insulin resistance / metabolic support'],
  },
  {
    id: 'if-mots-longevity',
    name: 'Iron Forge MOTS-c longevity',
    peptide: 'MOTS-c',
    source: 'Josh Holyfield / Iron Forge Peptide Mastery (Skool)',
    frequency: '3 injections per week',
    schedule: [{ weeks: '4–8 week cycles', dose: '5–10 mg per week total' }],
    flags: ['Goal: longevity / general wellness'],
  },
  {
    id: 'if-mito-seq',
    name: 'Iron Forge mito stack — sequential',
    peptide: 'SS-31 + NAD+ then MOTS-c + NAD+',
    source: 'Josh Holyfield / Iron Forge Peptide Mastery (Skool)',
    frequency: 'SS-31 daily; MOTS-c 3x/week; NAD+ 3x/week',
    schedule: [
      { weeks: '1–4', dose: 'SS-31 1–2 mg daily + NAD+ 100 mg 3x/week' },
      { weeks: '5–12', dose: 'MOTS-c 10 mg/week in 3 shots + NAD+ 100 mg 3x/week' },
      { weeks: 'then', dose: '4–8 weeks fully off; repeat 2–3 times per year' },
    ],
    flags: ['Tagged for significant mitochondrial dysfunction'],
  },
  {
    id: 'if-mito-conc',
    name: 'Iron Forge mito stack — concurrent',
    peptide: 'SS-31 + MOTS-c + NAD+',
    source: 'Josh Holyfield / Iron Forge Peptide Mastery (Skool)',
    frequency: 'SS-31 daily weeks 1–8; MOTS-c 3x/week; NAD+ 3x/week',
    schedule: [
      { weeks: '1–8', dose: 'SS-31 1–2 mg daily + MOTS-c 10 mg/week in 3 shots + NAD+ 100 mg 3x/week' },
      { weeks: '9–12', dose: 'Continue MOTS-c + NAD+ (SS-31 phase done)' },
      { weeks: 'then', dose: '4–8 weeks fully off; repeat 2–3 times per year' },
    ],
    flags: ['Tagged for moderate age-related decline, still active'],
  },
  {
    id: 'if-mito-prev',
    name: 'Iron Forge mito stack — prevention first',
    peptide: 'MOTS-c + NAD+ ± SS-31',
    source: 'Josh Holyfield / Iron Forge Peptide Mastery (Skool)',
    frequency: 'MOTS-c 3x/week; NAD+ 3x/week; SS-31 daily only if added',
    schedule: [
      { weeks: 'foundation', dose: 'MOTS-c 10 mg/week in 3 shots + NAD+ 100 mg 3x/week' },
      { weeks: '4–8 assess', dose: 'If still fatigued / poor recovery: add SS-31 1–2 mg daily for 4–8 weeks' },
      { weeks: 'maintenance', dose: 'Continue MOTS-c; 4 weeks off every 12–16 weeks' },
    ],
    flags: ['Tagged for younger or metabolically healthy'],
  },
  {
    id: 'if-ss31',
    name: 'Iron Forge SS-31 repair',
    peptide: 'SS-31',
    source: 'Josh Holyfield / Iron Forge Peptide Mastery (Skool)',
    frequency: 'Once daily, subcutaneous. No fasting, no time-of-day rule.',
    schedule: [{ weeks: '4–8 repair phase', dose: '1–2 mg per day' }],
    flags: ['Prep: 10 mg vial + 2 mL BAC ≈ 500 mcg per 10 units; 1 mg ≈ 20 units'],
  },
  {
    id: 'if-cjc-ipa-std',
    name: 'Iron Forge CJC-1295 (no DAC) + ipamorelin standard',
    peptide: 'CJC-1295 (no DAC) + Ipamorelin',
    source: 'Josh Holyfield / Iron Forge Peptide Mastery (Skool)',
    frequency: 'Once daily before bed, subcutaneous. Fasted ≥2 h after food; wait 30 min after injection before eating.',
    schedule: [
      { weeks: '12–16 on, then 4 off', dose: 'CJC 100–200 mcg + Ipa 100–200 mcg' },
    ],
    flags: [
      'By weight per injection: <150 lb 100–150 mcg; 150–200 lb 150–200 mcg; >200 lb 200–300 mcg',
      'Prep: 5 mg vial + 2 mL BAC ≈ 250 mcg per 10 units. Blend vial 5+5 mg + 2 mL: 4 units ≈ 100 mcg of each',
    ],
  },
  {
    id: 'if-cjc-ipa-split',
    name: 'Iron Forge CJC-1295 (no DAC) + ipamorelin split',
    peptide: 'CJC-1295 (no DAC) + Ipamorelin',
    source: 'Josh Holyfield / Iron Forge Peptide Mastery (Skool)',
    frequency: 'Twice daily: morning fasted + before bed',
    schedule: [{ weeks: 'same cycle as standard', dose: '100–150 mcg of each, twice daily' }],
    flags: ['Advanced split; two pulses per day'],
  },
  {
    id: 'if-cjc-solo',
    name: 'Iron Forge CJC-1295 without DAC (Mod GRF 1-29) solo',
    peptide: 'CJC-1295 (no DAC)',
    source: 'Josh Holyfield / Iron Forge Peptide Mastery (Skool)',
    frequency: 'Once daily (some protocols 2–3× daily). SubQ. Fasted, ≥2 hours after eating.',
    schedule: [{ weeks: '12–16 on, then 4 off', dose: '100–300 mcg per injection' }],
    flags: [
      'Fat-loss timing: before bed, fasted',
      'Muscle timing: morning, 30 min before first meal',
      'General: nighttime most common',
    ],
  },
  {
    id: 'if-tesa',
    name: 'Iron Forge tesamorelin standard',
    peptide: 'Tesamorelin',
    source: 'Josh Holyfield / Iron Forge Peptide Mastery (Skool)',
    frequency: 'Once daily, subcutaneous. 30–60 min before bed, fasted — or morning fasted, ≥2 hours before eating.',
    schedule: [{ weeks: 'continuous; labeled trials ≥26 weeks', dose: '2 mg (2000 mcg) once daily' }],
    flags: ['2 mg daily matches the FDA-labeled Egrifta dose'],
  },
  {
    id: 'if-serm-std',
    name: 'Iron Forge sermorelin standard',
    peptide: 'Sermorelin',
    source: 'Josh Holyfield / Iron Forge Peptide Mastery (Skool)',
    frequency: 'Once daily. 30 min before bed, empty stomach, ≥2 hours after eating.',
    schedule: [{ weeks: '3–6 months', dose: '200–500 mcg per injection' }],
    flags: [
      'Wellness / anti-aging: 200–300 mcg before bed',
      'Performance / recovery: 300–500 mcg before bed',
      'Max effect: 300 mcg morning fasted + 300 mcg before bed',
      'Prep note: 5 mg vial + 2 mL BAC ≈ 250 mcg per 10 units; 300 mcg ≈ 12 units',
    ],
  },
  {
    id: 'if-serm-ipa',
    name: 'Iron Forge sermorelin + ipamorelin',
    peptide: 'Sermorelin + Ipamorelin',
    source: 'Josh Holyfield / Iron Forge Peptide Mastery (Skool)',
    frequency: 'Daily, pinned together before bed, fasted',
    schedule: [{ weeks: '8–12', dose: 'Sermorelin 200–300 mcg + Ipamorelin 100–200 mcg' }],
    flags: [],
  },
  {
    id: 'if-ipa-solo',
    name: 'Iron Forge ipamorelin solo',
    peptide: 'Ipamorelin',
    source: 'Josh Holyfield / Iron Forge Peptide Mastery (Skool)',
    frequency: '1–2 times daily. Before bed and/or morning, fasted.',
    schedule: [{ weeks: '12–16 on, then 4 off', dose: '200–300 mcg per injection' }],
    flags: [],
  },
  {
    id: 'if-bpc-std',
    name: 'Iron Forge BPC-157 standard',
    peptide: 'BPC-157',
    source: 'Josh Holyfield / Iron Forge Peptide Mastery (Skool)',
    frequency: 'Once or twice daily. Morning and/or evening. No fasting required. SubQ preferred for a local injury; oral for gut.',
    schedule: [{ weeks: '4–8 active healing', dose: '250–500 mcg per day' }],
    flags: [
      'Practice pattern, not a published subQ dose-finding study',
      'By weight: <150 lb 200–300 mcg/day; 150–200 lb 300–400; >200 lb 400–500',
      'Acute injury: 400–500 mcg/day for 2–4 weeks, then reduce',
      'Chronic: 250–300 mcg/day for 6–8 weeks',
      'Gut: 250–500 mcg/day, oral preferred',
      'Post-surgical: 300–400 mcg/day, with surgeon approval',
      'Prep: 5 mg vial + 2 mL BAC ≈ 250 mcg per 10 units',
    ],
  },
  {
    id: 'if-tb500',
    name: 'Iron Forge TB-500 traditional',
    peptide: 'TB-500',
    source: 'Josh Holyfield / Iron Forge Peptide Mastery (Skool)',
    frequency: 'Loading: twice weekly (Mon/Thu or Tue/Fri). Maintenance: once every 1–2 weeks.',
    schedule: [
      { weeks: '4–6 loading', dose: '2–2.5 mg twice weekly (4–5 mg/week)' },
      { weeks: 'maintenance', dose: '2–2.5 mg once every 1–2 weeks, as needed' },
    ],
    flags: [
      'Acute: load 4–5 mg/week for 4–6 weeks',
      'Chronic: load 4–5 mg/week for 6–8 weeks',
      'Post-surgical: load 4–6 mg/week for 4–6 weeks, with surgeon approval',
      'General maintenance: 2–2.5 mg once every 2 weeks',
    ],
  },
  {
    id: 'if-wolverine',
    name: 'Iron Forge Wolverine stack',
    peptide: 'TB-500 + BPC-157',
    source: 'Josh Holyfield / Iron Forge Peptide Mastery (Skool)',
    frequency: 'Daily, subcutaneous, any time. No fasting required.',
    schedule: [{ weeks: '4–8 active healing', dose: 'TB-500 250–500 mcg/day + BPC-157 250–500 mcg/day' }],
    flags: ['Daily-stack recon: 5 mg vial + 2 mL BAC ≈ 250 mcg per 10 units'],
  },
  {
    id: 'if-ghk-std',
    name: 'Iron Forge GHK-Cu injectable',
    peptide: 'GHK-Cu',
    source: 'Josh Holyfield / Iron Forge Peptide Mastery (Skool)',
    frequency: 'Daily or 5 days per week, subcutaneous',
    schedule: [{ weeks: '4–8, can extend to 12; then 4–6 off', dose: '1–2 mg per day' }],
    flags: [
      'Practice pattern, not a published dose-finding study',
      'Prep: 50 mg vial + 2.5–3 mL BAC. At 2.5 mL, 1 mg ≈ 5 units. Blue color from copper is expected',
    ],
  },
  {
    id: 'if-ghk-low',
    name: 'Iron Forge GHK-Cu conservative start',
    peptide: 'GHK-Cu',
    source: 'Josh Holyfield / Iron Forge Peptide Mastery (Skool)',
    frequency: '3–5 times per week, subcutaneous',
    schedule: [{ weeks: 'until tolerance is known', dose: '0.5–1 mg per day' }],
    flags: ['Starting point before the 1–2 mg card'],
  },
  {
    id: 'if-ghk-topical',
    name: 'Iron Forge GHK-Cu topical',
    peptide: 'GHK-Cu',
    source: 'Josh Holyfield / Iron Forge Peptide Mastery (Skool)',
    frequency: 'Once or twice daily. Continuous, no cycle',
    schedule: [{ weeks: 'skin 8–16; hair 16–24', dose: '0.5–4% face; 2% eye area' }],
    flags: [],
  },
  {
    id: 'if-glow-vial',
    name: 'Iron Forge GLOW blend vial',
    peptide: 'GHK-Cu + BPC-157 + TB-500',
    source: 'Josh Holyfield / Iron Forge Peptide Mastery (Skool)',
    frequency: 'Subcutaneous. Healing: daily. Anti-aging: every other day. Maintenance: twice weekly.',
    schedule: [
      { weeks: '4–6 healing', dose: '5–10 units daily' },
      { weeks: '8–16 anti-aging', dose: '5–10 units every other day (3–4×/week)' },
      { weeks: 'maintenance', dose: '5–10 units twice weekly, as needed' },
    ],
    flags: [
      'Vial: TB-500 10 mg + BPC-157 10 mg + GHK-Cu 50 mg. Add 2 mL BAC (35 mg/mL total)',
      '10 units = 500 mcg TB-500 + 500 mcg BPC-157 + 2.5 mg GHK-Cu. About 20 days at 10 units daily',
      '10 units is 2.5 mg GHK-Cu, above the solo GHK-Cu 1–2 mg card',
      'Acute / post-surgical: daily 4–6 weeks, surgeon OK if after surgery',
    ],
  },
  {
    id: 'if-glow-separate',
    name: 'Iron Forge GLOW separate vials',
    peptide: 'GHK-Cu + BPC-157 + TB-500',
    source: 'Josh Holyfield / Iron Forge Peptide Mastery (Skool)',
    frequency: 'Daily, subcutaneous. Can start all three on day one.',
    schedule: [{ weeks: 'with the matching single-peptide cards', dose: 'GHK-Cu 1–2 mg + BPC-157 250–500 mcg + TB-500 250–500 mcg daily' }],
    flags: ['Separate shots, not the premixed GLOW vial'],
  },
  {
    id: 'if-klow',
    name: 'Iron Forge KLOW blend vial',
    peptide: 'TB-500 + BPC-157 + KPV + GHK-Cu',
    source: 'Josh Holyfield / Iron Forge Peptide Mastery (Skool)',
    frequency: 'Subcutaneous. Healing and gut: daily. Extended: every other day. Maintenance: twice weekly.',
    schedule: [
      { weeks: '4–6 healing + inflammation', dose: '5–10 units daily' },
      { weeks: '6–8 gut', dose: '5–10 units daily' },
      { weeks: '8–16 extended', dose: '5–10 units every other day (3–4×/week)' },
      { weeks: 'maintenance', dose: '5–10 units twice weekly, as needed' },
    ],
    flags: [
      'Vial: TB-500 10 mg + BPC-157 10 mg + KPV 10 mg + GHK-Cu 50 mg. Add 2 mL BAC (40 mg/mL total)',
      '10 units = 500 mcg TB-500 + 500 mcg BPC-157 + 500 mcg KPV + 2.5 mg GHK-Cu. About 20 days at 10 units daily',
      'Blend is for injection. After surgery, daily only with surgeon approval',
    ],
  },
  {
    id: 'if-ta1',
    name: 'Iron Forge thymosin alpha-1',
    peptide: 'Thymosin alpha-1',
    source: 'Josh Holyfield / Iron Forge Peptide Mastery (Skool)',
    frequency: 'Twice weekly (often Mon/Thu), subcutaneous. No fasting, no time-of-day rule.',
    schedule: [
      { weeks: '4–8 immune support; 4 off, or seasonal', dose: '1.6 mg (1600 mcg) per injection' },
      { weeks: '6–12 months chronic infection support', dose: '1.6 mg twice weekly' },
      { weeks: '2 weeks before a vaccine, then 2–4 weeks after', dose: '1.6 mg twice weekly' },
    ],
    flags: [
      '1.6 mg twice weekly matches thymalfasin (Zadaxin) labeled dosing where registered',
      'Chronic-infection row: source says physician supervision, often with other therapies',
      'Prep: 10 mg vial + 2 mL BAC ≈ 250 mcg per 5 units; 1.6 mg ≈ 32 units',
    ],
  },
  {
    id: 'if-selank-nasal',
    name: 'Iron Forge Selank intranasal',
    peptide: 'Selank',
    source: 'Josh Holyfield / Iron Forge Peptide Mastery (Skool)',
    frequency: '2–3 times daily. Morning and early afternoon preferred. No fasting.',
    schedule: [
      { weeks: '10–14 days (short / Russian clinical cycle)', dose: '200–400 mcg per dose; 400–1000 mcg/day' },
      { weeks: '4–6 extended community cycle', dose: '200–400 mcg per dose; 400–1000 mcg/day' },
    ],
    flags: ['1–3 weeks off between cycles. No taper on the source page'],
  },
  {
    id: 'if-selank-subq',
    name: 'Iron Forge Selank subcutaneous',
    peptide: 'Selank',
    source: 'Josh Holyfield / Iron Forge Peptide Mastery (Skool)',
    frequency: 'Once daily. Morning preferred. No fasting.',
    schedule: [{ weeks: '4–6; short option 10–14 days', dose: '100–300 mcg per day' }],
    flags: ['1–3 weeks off between cycles. No taper on the source page'],
  },
  {
    id: 'if-semax-nasal',
    name: 'Iron Forge Semax intranasal',
    peptide: 'Semax',
    source: 'Josh Holyfield / Iron Forge Peptide Mastery (Skool)',
    frequency: 'Once or twice daily. Morning or early afternoon. Avoid late-day dosing.',
    schedule: [{ weeks: '10–14 on, then 2–4 off; repeat as needed', dose: '200–600 mcg per day' }],
    flags: [
      'Cognitive: 200–400 mcg/day. Neuroprotection: 400–600. Post-injury: 600 mcg/day (source notes studies up to 6000 mcg)',
      'Nasal prep: 10 mg + 1 mL sterile saline, not BAC water. About 200 mcg per spray; about 50 sprays',
    ],
  },
  {
    id: 'if-semax-subq',
    name: 'Iron Forge Semax subcutaneous',
    peptide: 'Semax',
    source: 'Josh Holyfield / Iron Forge Peptide Mastery (Skool)',
    frequency: 'Once daily, morning',
    schedule: [{ weeks: '10–14 on, then 2–4 off', dose: '200–600 mcg per day' }],
    flags: ['Cognitive: 200–400 mcg/day. Neuroprotection: 400–600. Post-injury: 600 mcg/day'],
  },
  {
    id: 'if-dsip',
    name: 'Iron Forge DSIP',
    peptide: 'DSIP',
    source: 'Josh Holyfield / Iron Forge Peptide Mastery (Skool)',
    frequency: 'Once daily, subcutaneous, 30–60 min before bed',
    schedule: [{ weeks: '5–10 nights, then evaluate', dose: '100–300 mcg' }],
    flags: [
      'By weight: <150 lb 100–150 mcg; 150–200 lb 150–250; >200 lb 200–300',
      'Sleep: 100–200 mcg. Stress-related sleep: 200–300. GH-peptide sleep disruption: 100–200. Shift work: 200–300 before target sleep',
      'Prep: 10 mg vial + 2 mL BAC ≈ 500 mcg per 10 units; 200 mcg ≈ 4 units',
    ],
  },
  {
    id: 'if-pinealon',
    name: 'Iron Forge Pinealon',
    peptide: 'Pinealon',
    source: 'Josh Holyfield / Iron Forge Peptide Mastery (Skool)',
    frequency: 'Once daily, morning. Subcutaneous or intranasal.',
    schedule: [{ weeks: '10–20 days on, then 2–3 months off', dose: '100–300 mcg per day' }],
    flags: [
      'Neuroprotection or sleep/circadian: 100–200 mcg. Cognitive: 200–300 mcg',
      'Start at the low end of the range',
      'Off period is the Khavinson bioregulator convention; source says it is not from a published Pinealon dose-duration study',
      'Prep: 10 mg vial + 2 mL BAC ≈ 500 mcg per 10 units. About 50 doses at 200 mcg',
    ],
  },
  {
    id: 'if-epithalon',
    name: 'Iron Forge Epithalon',
    peptide: 'Epithalon',
    source: 'Josh Holyfield / Iron Forge Peptide Mastery (Skool)',
    frequency: 'Once daily, evening, subcutaneous',
    schedule: [{ weeks: '10–20 days; 2–3 cycles per year, several months between', dose: '500 mcg–1 mg per day' }],
    flags: [
      'Prep: 10 mg vial + 2 mL BAC ≈ 500 mcg per 10 units; 1 mg ≈ 20 units',
      'Stack named on the page (Epithalon + SS-31 + FOXO4-DRI) with no doses',
    ],
  },
  {
    id: 'if-nad-inj',
    name: 'Iron Forge NAD+ injectable',
    peptide: 'NAD+',
    source: 'Josh Holyfield / Iron Forge Peptide Mastery (Skool)',
    frequency: 'Subcutaneous or intramuscular. Morning preferred. Late doses may disrupt sleep.',
    schedule: [
      { weeks: '7–10 loading', dose: '100–200 mg daily' },
      { weeks: 'maintenance', dose: '50–100 mg, 1–3 times per week' },
    ],
    flags: [
      'IM uses the same 50–100 mg, 1–3×/week',
      'Needs more BAC than a typical peptide. 500 mg vial + 3 mL, or 1000 mg + 6 mL ≈ 167 mg/mL. 100 mg ≈ 60 units',
    ],
  },
  {
    id: 'if-niacin',
    name: 'Iron Forge niacin oral',
    peptide: 'Niacin',
    source: 'Josh Holyfield / Iron Forge Peptide Mastery (Skool)',
    frequency: 'Daily oral',
    schedule: [{ weeks: 'ongoing', dose: 'Start 100–250 mg; standard 500–1000 mg' }],
    flags: ['Flush (redness, warmth, itching about 20–30 min) while tolerance builds'],
  },
  {
    id: 'if-nmn',
    name: 'Iron Forge NMN oral',
    peptide: 'NMN',
    source: 'Josh Holyfield / Iron Forge Peptide Mastery (Skool)',
    frequency: 'Daily oral',
    schedule: [{ weeks: 'ongoing', dose: 'Start 250–500 mg; standard 500–1000 mg' }],
    flags: ['Source notes FDA flagged NMN in 2022; regulatory status uncertain'],
  },
  {
    id: 'if-nr',
    name: 'Iron Forge NR oral',
    peptide: 'NR',
    source: 'Josh Holyfield / Iron Forge Peptide Mastery (Skool)',
    frequency: 'Daily oral',
    schedule: [{ weeks: 'ongoing', dose: 'Start 250–500 mg; standard 500–1000 mg' }],
    flags: ['Dietary supplement (Tru Niagen and similar)'],
  },
  {
    id: 'if-foxo4',
    name: 'Iron Forge FOXO4-DRI',
    peptide: 'FOXO4-DRI',
    source: 'Josh Holyfield / Iron Forge Peptide Mastery (Skool)',
    frequency: 'Subcutaneous, every other day, 3 doses total. Repeat 1–3 times per year.',
    schedule: [
      { weeks: '3 doses, every other day', dose: 'Conservative 2–3 mg; standard 3–5 mg; aggressive 5–10 mg' },
      { weeks: 'alternative, less precedent', dose: '0.3–0.5 mg daily for 7 days, every other week' },
    ],
    flags: [
      'Standard table is labeled community consensus',
      'Prep: 10 mg vial + 1 mL BAC = 10 mg/mL. 5 mg ≈ 50 units',
      'Named in a repair phase with SS-31 and Epithalon; no combined dose table',
    ],
  },
  {
    id: 'if-pt141',
    name: 'Iron Forge PT-141',
    peptide: 'PT-141',
    source: 'Josh Holyfield / Iron Forge Peptide Mastery (Skool)',
    frequency: 'As needed, 45–60 min before sexual activity. Subcutaneous, abdomen or thigh.',
    schedule: [
      { weeks: 'as needed', dose: '1–2 mg; max 1 dose per 24 hours, 8 doses per month' },
      { weeks: 'nausea-sensitive start', dose: '0.5 mg first use, then 0.75 mg, then 1 mg' },
    ],
    flags: [
      'Labeled community practice, not a published dose-finding study',
      'Page says both PT-141 and a PDE5 inhibitor can affect blood pressure; watch for lightheadedness. No combined dose table',
      'Prep: 10 mg vial + 2 mL BAC ≈ 500 mcg per 10 units. 1 mg ≈ 20 units; 1.75 mg ≈ 35; 2 mg ≈ 40',
    ],
  },
  {
    id: 'if-oxytocin',
    name: 'Iron Forge oxytocin',
    peptide: 'Oxytocin',
    source: 'Josh Holyfield / Iron Forge Peptide Mastery (Skool)',
    frequency: 'As needed. Nasal may also be daily for stress. Alternate nostrils if sprayed.',
    schedule: [
      { weeks: 'intranasal', dose: '20–40 IU, 20–30 min before' },
      { weeks: 'sublingual troche', dose: 'Physician prescribed, typically 10–100 IU, 30–45 min before' },
      { weeks: 'subcutaneous', dose: '4–10 mcg, 30 min before' },
    ],
    flags: [
      'Page says practice patterns plus published research doses adapted by practitioners',
      'Same-day use with PT-141 is named; no combined dose table. TRT heading has no dose',
    ],
  },
  {
    id: 'if-mt2',
    name: 'Iron Forge Melanotan II',
    peptide: 'Melanotan II',
    source: 'Josh Holyfield / Iron Forge Peptide Mastery (Skool)',
    frequency: 'Subcutaneous, abdomen or thigh. Before bed. Start 0.1–0.25 mg for nausea.',
    schedule: [
      { weeks: '7–14 loading, until desired tan', dose: '0.25–0.5 mg daily' },
      { weeks: 'maintenance', dose: '0.25–0.5 mg, 2–3 times per week, or only before planned sun' },
    ],
    flags: [
      'Loading by weight: <150 lb 0.25 mg; 150–200 lb 0.25–0.5 mg; >200 lb 0.5 mg daily',
      'Trials used 0.01–0.03 mg/kg daily (about 0.7–2.1 mg at 70 kg). Loading/maintenance table is labeled community practice, not a published dose-finding study',
      'Named with a GLP-1 (retatrutide, semaglutide, tirzepatide); page says appetite suppression may stack, watch under-eating. No combined dose table',
      'Prep: 10 mg vial + 2 mL BAC ≈ 500 mcg per 10 units. 0.25 mg ≈ 5 units; 0.5 mg ≈ 10; 1 mg ≈ 20',
    ],
  },
  {
    id: 'if-kiss',
    name: 'Iron Forge kisspeptin',
    peptide: 'Kisspeptin',
    source: 'Josh Holyfield / Iron Forge Peptide Mastery (Skool)',
    frequency: 'Every other day, subcutaneous. Morning or evening. No fasting.',
    schedule: [{ weeks: '4–8', dose: '100–200 mcg' }],
    flags: [
      'By weight: <150 lb 100 mcg; 150–200 lb 100–150; >200 lb 150–200. Every other day',
      'Labs on the page: baseline and 4 weeks. LH, total and free testosterone, estradiol, FSH',
      'Named with enclomiphene. Page says no published human research on that pair. No combined dose',
      'Prep: 5 mg vial + 2 mL BAC ≈ 250 mcg per 10 units. 100 mcg ≈ 4 units; 150 ≈ 6; 200 ≈ 8',
    ],
  },
  {
    id: 'if-hcg',
    name: 'Iron Forge hCG',
    peptide: 'hCG',
    source: 'Josh Holyfield / Iron Forge Peptide Mastery (Skool)',
    frequency: 'Subcutaneous',
    schedule: [
      { weeks: 'with TRT, ongoing', dose: '250–500 IU, 3×/week (750–1500 IU/week)' },
      { weeks: 'monotherapy, ongoing', dose: '500–1000 IU, 3×/week (1500–3000 IU/week)' },
      { weeks: 'fertility, 3–6 months minimum', dose: '500 IU every other day' },
    ],
    flags: [
      'Fertility: if sperm count does not recover, page says add hMG or rFSH 75 IU every other day. Semen analysis every 3 months. Full recovery may take 12–24 months',
      'Page says clinical practice patterns. No vial size on the reconstitution shot',
    ],
  },
  {
    id: 'if-kpv',
    name: 'Iron Forge KPV solo',
    peptide: 'KPV',
    source: 'Josh Holyfield / Iron Forge Peptide Mastery (Skool)',
    frequency: 'Route depends on use. Separate from the KLOW blend card.',
    schedule: [
      { weeks: '4–8 subQ', dose: '200–400 mcg once daily' },
      { weeks: '4–8 oral, can extend with monitoring', dose: '200–500 mcg once or twice daily' },
      { weeks: 'topical, as needed', dose: '0.01–0.1% cream, twice daily' },
    ],
    flags: [
      'SubQ tagged systemic inflammation. Oral tagged gut. Topical tagged eczema, psoriasis, wound healing',
      'Prep for injectable: 5 mg vial + 1 mL BAC ≈ 250 mcg per 5 units. Refrigerate after mixing',
      'KPV + BPC-157 is a title only; no combined dose',
    ],
  },
  {
    id: 'if-ha',
    name: 'Iron Forge oral hyaluronic acid',
    peptide: 'Hyaluronic acid',
    source: 'Josh Holyfield / Iron Forge Peptide Mastery (Skool)',
    frequency: 'Daily oral, with food',
    schedule: [
      { weeks: '8–12 skin hydration', dose: '100–120 mg' },
      { weeks: '12+ skin anti-aging', dose: '120–200 mg' },
      { weeks: '12+ joint support', dose: '200 mg' },
      { weeks: 'ongoing wellness', dose: '100 mg' },
    ],
    flags: ['Page says first change at 2–4 weeks, fuller effect at 8–12 weeks. Joint row says best with exercise'],
  },
]

