export const LIBRARY = [
  {
    id: 'jh-home',
    type: 'site',
    creator: 'Josh Holyfield',
    title: 'Josh Holyfield — public site (Rumble rebuild)',
    url: 'https://joshholyfield.com/',
    tags: ['Holyfield', 'Rumble', 'CJC-1295', 'Ipamorelin'],
    note: 'YouTube channel removed Aug 2026. Site points to current public videos. Do not scrape Skool.',
  },
  {
    id: 'jh-rumble-ban',
    type: 'video',
    creator: 'Josh Holyfield',
    title: 'The Real Reason I Got Banned From YouTube | Weekly Q&A #11',
    url: 'https://rumble.com/v7euwsk-the-real-reason-i-got-banned-from-youtube-weekly-q-and-a-11.html',
    tags: ['Holyfield', 'policy', 'Rumble'],
    note: 'Public Rumble upload after the YouTube takedown.',
  },
  {
    id: 'jh-aicar',
    type: 'video',
    creator: 'Josh Holyfield',
    title: 'What Is AICAR? (Rumble)',
    url: 'https://rumble.com/v7ee06g-what-is-aicar-the-exercise-in-a-pill-that-started-it-all.html',
    tags: ['Holyfield', 'MOTS-c', 'AICAR'],
    note: 'Public Rumble. Educational link only.',
  },
  {
    id: 'jh-tracker',
    type: 'tool',
    creator: 'Josh Holyfield',
    title: 'His public peptide/supplement tracker',
    url: 'https://tracker.joshholyfield.com',
    tags: ['Holyfield', 'tool'],
    note: 'Third-party tool. Link, do not copy.',
  },
  {
    id: 'tb-longevity',
    type: 'video',
    creator: 'Trevor Bachmeyer',
    title: 'My 4 Personal Favorite Longevity Peptides',
    url: 'https://www.youtube.com/watch?v=ZrkJu8nzsTw',
    tags: ['Bachmeyer', 'Retatrutide', 'BPC-157', 'MOTS-c'],
    note: 'Older upload; some Bachmeyer YT inventory was later removed. Link may 404.',
  },
  {
    id: 'tb-bpc',
    type: 'video',
    creator: 'Trevor Bachmeyer',
    title: 'BPC157 Does Everything',
    url: 'https://youtu.be/O_hbAtgMSE8',
    tags: ['Bachmeyer', 'BPC-157'],
    note: 'Same caveat as other pre-takedown Bachmeyer videos.',
  },
  {
    id: 'tb-gh',
    type: 'video',
    creator: 'Trevor Bachmeyer',
    title: 'The Ultimate Endogenous GH Stack (Rumble)',
    url: 'https://rumble.com/v7895x0-the-ultimate-endogenous-gh-stack-dr-trevor-bachmeyer.html',
    tags: ['Bachmeyer', 'CJC-1295', 'Ipamorelin', 'Tesamorelin'],
    note: 'Public Rumble mirror of the GH stack talk.',
  },
  {
    id: 'tb-mix',
    type: 'video',
    creator: 'Trevor Bachmeyer',
    title: 'Peptide Mixing Mistakes: GHK-Cu, BPC-157 & Ipamorelin',
    url: 'https://www.youtube.com/watch?v=PoASRdbWTRk',
    tags: ['Bachmeyer', 'GHK-Cu', 'BPC-157', 'Ipamorelin'],
    note: 'Check live before relying on the embed.',
  },
  {
    id: 'af-fast',
    type: 'video',
    creator: 'Ashley Froese DO',
    title: 'Learn Peptides So Fast it\'s UNREAL',
    url: 'https://www.youtube.com/watch?v=TT0V9oVDwbY',
    tags: ['Froese', 'overview', 'BPC-157', 'TB-500'],
    note: 'Public YouTube explainer. Course upsells are his/hers — we only link the free video.',
  },
  {
    id: 'af-7min',
    type: 'video',
    creator: 'Ashley Froese DO',
    title: 'Doctor Explains Peptides in 7 Minutes',
    url: 'https://www.youtube.com/watch?v=dVkS5SEP8o0',
    tags: ['Froese', 'overview'],
    note: 'Short public primer.',
  },
  {
    id: 'af-roadmap',
    type: 'video',
    creator: 'Ashley Froese DO',
    title: 'If I Started Peptides Today, I\'d Do THIS',
    url: 'https://www.youtube.com/watch?v=LQhIvUKrVTo',
    tags: ['Froese', 'roadmap'],
    note: 'Public YouTube.',
  },
  {
    id: 'af-reta',
    type: 'video',
    creator: 'Ashley Froese DO',
    title: 'Why Retatrutide is KING of Fat Loss Peptides',
    url: 'https://www.youtube.com/watch?v=ukCySPXN0WU',
    tags: ['Froese', 'Retatrutide'],
    note: 'Public YouTube. Opinion content, not a trial.',
  },
  {
    id: 'af-channel',
    type: 'channel',
    creator: 'Ashley Froese DO',
    title: 'This Is Not Covered — channel',
    url: 'https://youtube.com/@drafroese',
    tags: ['Froese'],
    note: 'Index of public videos.',
  },
  {
    id: 'jm-home',
    type: 'article',
    creator: 'Joe Mars',
    title: 'Joe Mars Report (Substack archive)',
    url: 'https://joemarsreport.substack.com/archive',
    tags: ['Mars', 'policy', 'research'],
    note: 'Public archive. Paid/Skool material stays off this app.',
  },
  {
    id: 'jm-fda',
    type: 'article',
    creator: 'Joe Mars',
    title: 'RFK / FDA compounding peptides context',
    url: 'https://joemarsreport.substack.com/p/rfk-wants-to-bring-back-14-peptides',
    tags: ['Mars', 'FDA', 'CJC-1295', 'Ipamorelin'],
    note: 'Public post on compounding category changes.',
  },
  {
    id: 'jm-warning',
    type: 'article',
    creator: 'Joe Mars',
    title: 'FDA warning letters to peptide companies',
    url: 'https://joemarsreport.substack.com/p/the-fda-is-coming-for-peptide-companies',
    tags: ['Mars', 'FDA'],
    note: 'Public post. Educational, not legal advice.',
  },
  {
    id: 'jm-stack',
    type: 'article',
    creator: 'Joe Mars',
    title: 'Superman Stack (five-role framing)',
    url: 'https://joemarsreport.substack.com/p/the-superman-stack-if-i-could-pick-b27',
    tags: ['Mars', 'Tesamorelin', 'BPC-157', 'MOTS-c'],
    note: 'Author opinion piece. Link out; do not republish the essay.',
  },
  {
    id: 'pubmed-bpc-ortho',
    type: 'research',
    creator: 'HSS Journal / PubMed',
    title: 'Emerging Use of BPC-157 in Orthopaedic Sports Medicine (systematic review)',
    url: 'https://pubmed.ncbi.nlm.nih.gov/40756949/',
    tags: ['BPC-157', 'research'],
    note: 'Peer-reviewed review. Mostly preclinical.',
  },
  {
    id: 'pubmed-bpc-pharm',
    type: 'research',
    creator: 'PubMed',
    title: 'BPC-157 as an Investigational Peptide: biopharmaceutical barriers (2026)',
    url: 'https://pubmed.ncbi.nlm.nih.gov/42198317/',
    tags: ['BPC-157', 'research'],
    note: 'States no approved formulation and thin human data.',
  },
]
